-- Drop and recreate Users table (Example)

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  is_admin BOOLEAN DEFAULT FALSE
);

DROP TABLE IF EXISTS cats CASCADE;
CREATE TABLE cats (
  id SERIAL PRIMARY KEY NOT NULL,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  main_photo_url VARCHAR(255) NOT NULL,
  fee INTEGER NOT NULL DEFAULT 0,
  age SMALLINT,
  region VARCHAR(255),
  size VARCHAR(255),
  species VARCHAR(255),
  is_available BOOLEAN DEFAULT TRUE
);

DROP TABLE IF EXISTS favourites CASCADE;
CREATE TABLE favourites (
  user_id INTEGER REFERENCES users(id) NOT NULL,
  cat_id INTEGER REFERENCES cats(id) NOT NULL
);
